CREATE OR REPLACE PROCEDURE STUDENT4.add_logs (p_function    VARCHAR2,
                                               p_text_err    VARCHAR2)
AS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO STUDENT4.logs (function_err, text_err)
         VALUES (p_function, p_text_err);

    COMMIT;
END;
/


GRANT EXECUTE ON STUDENT4.ADD_LOGS TO JKH
/

GRANT EXECUTE ON STUDENT4.ADD_LOGS TO STUDENT1
/

GRANT EXECUTE ON STUDENT4.ADD_LOGS TO STUDENT2
/

GRANT EXECUTE ON STUDENT4.ADD_LOGS TO STUDENT3
/
